# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #configuracao da instancia da autoridade certificadora (CA)
  config.vm.define "scylla1" do |host|
    host.vm.box = "ubuntu/xenial64"

    host.vm.network "private_network", ip: "192.168.56.51"
    host.vm.hostname = "scylla1.infobarbosa.github.com"
    host.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
      v.name = "scylla1.vagrant"
    end

    host.vm.provision "shell", path: "install_scylla.sh", privileged: false
  end

  config.vm.define "scylla2" do |host|
    host.vm.box = "ubuntu/xenial64"

    host.vm.network "private_network", ip: "192.168.56.52"
    host.vm.hostname = "scylla2.infobarbosa.github.com"
    host.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
      v.name = "scylla2.vagrant"
    end

    host.vm.provision "shell", path: "install_scylla.sh", privileged: false
  end

end
